#############################
#   merge_metadata.R
#############################
# This script reads metadata tables generated by
# main_find_classes.R and main_find_classes_exp-split.R
# and it creates a single final table
#############################
# author = apascualgarcia.github.io
# April 7th, 2023. ETH-Zürich
#############################

rm(list=ls())
this.dir=strsplit(rstudioapi::getActiveDocumentContext()$path, "/src/")[[1]][1]
dirSrc=paste(this.dir,"/src/",sep="") # Directory where the code is
setwd(dirSrc)
setwd("../7.1_classes")
fileIn1 = "metadata_Time0D-7D-4M_May2022_wJSDpart-split.csv"
sample_md1 = read.table(fileIn1, sep="\t", header = T) # this will be the reference

fileIn2 = "metadata_Time0D-7D-4M_May2022_Time0D_7D_4M_wJSDpart-all.csv"
sample_md2 = read.table(fileIn2,sep="\t", header = T)

fileIn3 = "metadata_Time0D-7D-4M_May2022_Time0D_7D_wJSDpart-all.csv"
sample_md3 = read.table(fileIn3, sep="\t", header = T)

fileIn4 = "metadata_Time0D-7D-4M_May2022_Time0D_7D_matched_wJSDpart-all.csv"
sample_md4 = read.table(fileIn4, sep="\t", header = T)

fileOut = "metadata_Time0D-7D-4M_May2022_wJSDpart-merged.csv"

#  Merge metadata ----

sample_md = sample_md1

# ... add first partition
sample_md$Time0D_7D_4M = NA
matched = match(sample_md2$sampleid, sample_md$sampleid)
sample_md$Time0D_7D_4M[matched] = sample_md2$Time0D_7D_4M

# ... second
sample_md$Time0D_7D = NA
matched = match(sample_md3$sampleid, sample_md$sampleid)
sample_md$Time0D_7D[matched] = sample_md3$Time0D_7D

# ... third
sample_md$Time0D_7D_matched = NA
matched = match(sample_md4$sampleid, sample_md$sampleid)
sample_md$Time0D_7D_matched[matched] = sample_md4$Time0D_7D_matched

# the alternative with merge didn't work as expected
# sample_md = merge(sample_md1, sample_md2) #, by = "sampleid", all.x = T)
# sample_md = merge(sample_md, sample_md3, all.x = T)
# sample_md = merge(sample_md, sample_md4, all.x = T)

# Write output -----
write.table(sample_md, file = fileOut, sep = "\t", quote = F)

# Check differences between partitions
part_diff = sample_md$Part_Time7D_rep1_2 - sample_md$Time0D_7D_matched
part_diff = part_diff[!is.na(part_diff)]
length(which(part_diff == 1)) # 1
length(which(part_diff == -1)) # 8

part_diff = sample_md$Part_Time7D_rep2_2 - sample_md$Time0D_7D_matched
part_diff = part_diff[!is.na(part_diff)]
length(which(part_diff == 1)) # 8
length(which(part_diff == -1)) # 1

part_diff = sample_md$Part_Time7D_rep3_2 - sample_md$Time0D_7D_matched
part_diff = part_diff[!is.na(part_diff)]
length(which(part_diff == 1)) # 10
length(which(part_diff == -1)) # 0

part_diff = sample_md$Part_Time7D_rep4_2 - sample_md$Time0D_7D_matched
part_diff = part_diff[!is.na(part_diff)]
length(which(part_diff == 1)) # 2
length(which(part_diff == -1)) # 3
